### ISSUE TITLE
some words throw an error

### ISSUE THREAD

**Issue by syelluru** [Manwholikespie/thesaurus-api#6]
s = Word("unregister")
s.synonyms() throws an error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "thesaurus.py", line 199, in synonyms
    data = [x['syn'] if 'syn' in x else [] for x in self.filter(defnNum=defnNum, filters=filters)]
  File "thesaurus.py", line 172, in filter
    c_def = self.data[x]
IndexError: list index out of range

**Comment by syelluru** [comment]
![screen shot 2018-01-18 at 12 49 12 pm](https://user-images.githubusercontent.com/22226581/35126727-5a534d5a-fc74-11e7-9a8d-0dae39f8b797.png)

**Comment by syelluru** [comment]
![screen shot 2018-01-18 at 5 23 34 pm](https://user-images.githubusercontent.com/22226581/35126739-68761548-fc74-11e7-9741-9bc9277c62ef.png)

**Comment by Manwholikespie** [comment]
It throws that error when thesaurus.com does not have an entry for the requested word.
That used to be the first thing I checked for when grabbing data. Strange that I missed adding that to the Word class when I threw out the old functions.

Thanks for reporting this to me. Easiest thing I can think to do would be to just have all the functions return empty versions of their usual types. Ex: myWord.synonyms() would return an empty list, myWord.origin() returns an empty unicode string, etc.

Or would you prefer it throw a specific type of error?

**Comment by syelluru** [comment]
Hi Manwholikespie!
Thanks for getting back. In my opinion, I feel that it should not throw an error, instead just return an empty list. I fixed this issue by gracefully handling this error by doing the aforementioned. Let me know if and when you fix this issue. 

Thanks 👍

**Comment by syelluru** [comment]
![screen shot 2018-01-19 at 3 56 16 pm](https://user-images.githubusercontent.com/22226581/35173520-5b4f86d4-fd31-11e7-8cbb-34ac4c62e771.png)

**Comment by Manwholikespie** [comment]
Sorry it took so long. Got busy. At the top of the filter function, I now check if the amount of word definitions is 0. If so, it returns an empty list. Thus, synonyms() and antonyms() returns an empty list as well.

Btw, expect the name of the repo to change soon. As detailed in #4 , you can't import from the thesaurus-api folder due to the dash in its name. I'll probably name it thesaurusAPI or something.

Thanks again for reporting this :)
